Updated the format of the output

diff --git a/bin/syntax-check b/bin/syntax-check
--- a/bin/syntax-check
+++ b/bin/syntax-check
@@ -1,3 +1,32 @@
 #!/bin/bash
 
-find . -type f -name "*.js" | grep -v 'node_modules' |  while read -r line; do echo "$line"; node -c $line; done;
+total=0
+success=0
+errors=""
+
+printf "\t\x1b[34mSyntax check of files:\x1b[0m\n\n"
+
+for line in `find . -type f -name "*.js" | grep -v 'node_modules'`
+do
+  (( total++ ))
+  error=`node -c $line 2>&1 `
+  if [ "$error" ]
+  then
+    errors="$errors\x1b[31m$error\x1b[0m\n\n\x1b[36m---\x1b[0m\n\n"
+    printf "\t\x1b[31m  $line\x1b[0m\n"
+  else
+    (( success++ ))
+    printf "\t\x1b[32m\xE2\x9C\x94\x1b[0m \x1b[90m$line\x1b[0m\n"
+  fi;
+done
+
+if [ "$total" != "$success" ]
+then
+  printf "\n\x1b[36m---\x1b[0m\n\n"
+  printf "$errors"
+  exit 1;
+else
+  printf "\n\t\x1b[34mSuccessful syntax check of $total files\x1b[0m"
+fi;
+
+printf "\n\n"
